### ISSUE TITLE
Reordering menu tabs

### ISSUE THREAD

**Issue by achterbahn** [bezumkin/orbita#3]
In the admin panel, a more logical order of the tabs would be:

Topics / Topics
Videos / Videos
Notifications / Benachrichtigungen
Pages / Seiten
"space"
Subscriptions / Abos
Settings / Einstellungen
"space"
Users / Benutzer
Roles / Benutzerrollen

**Comment by bezumkin** [comment]
@achterbahn Now you can specify new system setting in `.env`:
```
ADMIN_SECTIONS="topics,videos,notifications,pages,-,levels,settings,-,users,roles"
```

![Screenshot 2024-05-29 at 10 01 50](https://github.com/bezumkin/orbita/assets/1257284/4f6ec6d3-7858-4465-a1a2-e85c14ecb216)
