### ISSUE TITLE
В настройках профиля не работает изменение пароля.

### ISSUE THREAD

**Issue by inetlover** [bezumkin/orbita#4]
При сохранении нового пароля поле  “Пароль” остается пустым и новый пароль не работает при авторизации.

**Comment by inetlover** [comment]
Проблема только на сайте orbita.bezumkin.ru, на локальном ее нет.
Не возможно войти по паролю, говорит что веден не верный. То есть, если в настройках поменять пароль, то больше на сайт по паролю не войти, придется каждый раз его восстанавливать.
Спасибо, я думал может есть какая-нибудь связь то что поле Пароль остается пустым без звездочек.

**Comment by bezumkin** [comment]
@inetlover Мне кажется, тебе какой-нибудь менеджер паролей на твоём компе мешает. Потому что я даже на твоей учётке проверяю, и не вижу проблемы.

https://github.com/bezumkin/orbita/assets/1257284/324b705f-f371-48ff-afe9-588379d44a1e

Попробуй проверить на другом компьютере или телефоне, должно работать. Сейчас пароль стоит случайный, так что нужно будет опять сбросить.

**Comment by inetlover** [comment]
> Попробуй проверить на другом компьютере или телефоне

Попробовал на телефоне, менял браузеры, менеджером паролей в браузере не пользуюсь и везде одна проблема, после смены пароля, выхожу и пытаюсь войти по новому паролю и вижу: "Неверный логин или пароль",  ((

**Comment by inetlover** [comment]
Разобрался!
Если пишем логин - то тогда впускает, а если e-mail - то нет.
